# Generated by Django 3.2.18 on 2023-05-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='key',
            field=models.CharField(blank=True, choices=[('Расходы', 'Расходы'), ('Доходы', 'Доходы')], default='Расходы', max_length=100),
        ),
    ]
